---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "operator.operator.name" . }}
  labels:
    {{- include "operator.operator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "operator.operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "operator.operator.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "operator.operator.name" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
          image: "{{ include "operator.image" . }}"
          imagePullPolicy: IfNotPresent
          args:
            - operator
            {{- if .Values.operator.cloudflareToken }}
            - --cloudflare-token={{ .Values.operator.cloudflareToken }}
            {{- end }}
            {{- if .Values.operator.healthBindAddress }}
            - --health-bind-address={{ .Values.operator.healthBindAddress }}
            {{- end }}
            {{- if .Values.operator.logLevel }}
            - --log-level={{ .Values.operator.logLevel }}
            {{- end }}
            {{- if .Values.operator.routerOsAddress }}
            - --routeros-address={{ .Values.operator.routerOsAddress }}
            {{- end }}
            {{- if .Values.operator.routerOsPassword }}
            - --routeros-password={{ .Values.operator.routerOsPassword }}
            {{- end }}
            {{- if .Values.operator.routerOsUsername }}
            - --routeros-username={{ .Values.operator.routerOsUsername }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8888
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8888
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.operator.resources | nindent 12 }}
          {{- if .Values.operator.externalSecret }}
          envFrom:
            - secretRef:
                name:  {{ .Values.operator.externalSecret }}
          {{- end }}
