{{- if .Values.operator.rbac.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "operator.operator.clusterRoleName" . }}
  labels:
    {{- include "operator.operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "operator.operator.clusterRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "operator.operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
