---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "operator.server.name" . }}
  labels:
    {{- include "operator.server.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "operator.server.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "operator.server.name" . }}
    namespace: {{ .Release.Namespace }}
