---
# -- Override the fully qualified name of resources created by this chart
nameOverride: ""

# -- Define settings for the operator workload
operator:
  # --- Specify the cloudflare token to use with the operator
  cloudflareToken: ""

  # --- Specify an external secret ref whose environment variables will be mounted into the operator's container
  externalSecret: ""

  # --- Specify the address to bind the health endpoints to
  healthBindAddress: ""

  # --- Specify the logging verbosity
  logLevel: ""

  # -- Sets the operator pod's resource requests and limits
  resources: {}

  # --- Specify the routeros device address to connect to
  routerOsAddress: ""

  # --- Specify the password to the routeros device address to connect to
  routerOsPassword: ""

  # --- Specify the username to the routeros device address to connect to
  routerOsUsername: ""

# -- Define settings for the server workload
server:
  # --- Specify an external secret ref whose environment variables will be mounted into the server's container
  externalSecret: ""

  # --- Specify server ingress
  ingress:
    # -- Additional ingress annotations
    annotations: {}

    # -- Enable an ingress resource for the access-operator server
    enabled: false

    # -- Specify the hostname for the ingress resource
    hostname: ""

    # -- Specify the ingress class name for the ingress resource
    ingressClassName: ""

    # -- Specify the root path for the ingress resource
    path: /

    # -- Specify the ingress path type for the ingress rule
    pathType: Prefix

  # --- Specify the logging verbosity
  logLevel: ""

  # -- Sets the server pod's resource requests and limits
  resources: {}
