apiVersion: v1
entries:
  crds:
  - apiVersion: v2
    appVersion: 0.1.0-rc.11
    created: "2024-11-04T22:39:47.206843532Z"
    description: CRDs for the access-operator
    digest: eb71ba37a9121971e0b3beed75723b6015bed07252fcc3570cadf19a11d46afb
    name: crds
    type: application
    urls:
    - https://benfiola.github.io/access-operator/charts/crds-0.1.0-rc.11.tgz
    version: 0.1.0-rc.11
  - apiVersion: v2
    appVersion: 0.1.0-rc.10
    created: "2024-11-04T22:39:47.206009986Z"
    description: CRDs for the access-operator
    digest: 09d2b2028492cf368bdd3c3782cd9d3f972385509d76f9262378b33b8befb6cc
    name: crds
    type: application
    urls:
    - https://benfiola.github.io/access-operator/charts/crds-0.1.0-rc.10.tgz
    version: 0.1.0-rc.10
  - apiVersion: v2
    appVersion: 0.1.0-rc.9
    created: "2024-11-04T22:39:47.210119176Z"
    description: CRDs for the access-operator
    digest: b156f0d53136b24236a302500003e3e04989326bf43623d62cd48c6685f700f4
    name: crds
    type: application
    urls:
    - https://benfiola.github.io/access-operator/charts/crds-0.1.0-rc.9.tgz
    version: 0.1.0-rc.9
  - apiVersion: v2
    appVersion: 0.1.0-rc.8
    created: "2024-11-04T22:39:47.209190843Z"
    description: CRDs for the access-operator
    digest: 4f2e429f9203c3e6082a6c3585c0fd151f72e01267e18bd3e52a008723e186f0
    name: crds
    type: application
    urls:
    - https://benfiola.github.io/access-operator/charts/crds-0.1.0-rc.8.tgz
    version: 0.1.0-rc.8
  - apiVersion: v2
    appVersion: 0.1.0-rc.7
    created: "2024-11-04T22:39:47.207859849Z"
    description: CRDs for the access-operator
    digest: a57135403678325be8b987d89661c2fe3713e8fbe8303fa489970e26f01d38c4
    name: crds
    type: application
    urls:
    - https://benfiola.github.io/access-operator/charts/crds-0.1.0-rc.7.tgz
    version: 0.1.0-rc.7
  - apiVersion: v2
    appVersion: 0.1.0-rc.3
    created: "2024-11-04T22:39:47.207049416Z"
    description: CRDs for the access-operator
    digest: cd3979af8fa6be0ce4543daf8b1e14e1c3d702843d647d0c0191bd74fef6814e
    name: crds
    type: application
    urls:
    - https://benfiola.github.io/access-operator/charts/crds-0.1.0-rc.3.tgz
    version: 0.1.0-rc.3
  - apiVersion: v2
    appVersion: 0.1.0-rc.2
    created: "2024-11-04T22:39:47.20694419Z"
    description: CRDs for the access-operator
    digest: 6608901f6a216cef2da91492a0c8d0933f1a0e229b7c8cb41befd3b917a8086c
    name: crds
    type: application
    urls:
    - https://benfiola.github.io/access-operator/charts/crds-0.1.0-rc.2.tgz
    version: 0.1.0-rc.2
  - apiVersion: v2
    appVersion: 0.1.0-rc.1
    created: "2024-11-04T22:39:47.20519234Z"
    description: CRDs for the access-operator
    digest: d70e3e080773021c13dd3004723f3904cc85aeb232f876efa0da2058ba492876
    name: crds
    type: application
    urls:
    - https://benfiola.github.io/access-operator/charts/crds-0.1.0-rc.1.tgz
    version: 0.1.0-rc.1
  operator:
  - apiVersion: v2
    appVersion: 0.1.0-rc.11
    created: "2024-11-04T22:39:47.211419664Z"
    description: Manages external access into benfiola's homelab
    digest: c500f90c8a2859af7820c4d4282542752b6ad1d3ce88fd8815cdd9666da38af0
    name: operator
    type: application
    urls:
    - https://benfiola.github.io/access-operator/charts/operator-0.1.0-rc.11.tgz
    version: 0.1.0-rc.11
  - apiVersion: v2
    appVersion: 0.1.0-rc.10
    created: "2024-11-04T22:39:47.210976847Z"
    description: Manages external access into benfiola's homelab
    digest: 855f30d8c93ecc461926d3d931c507159d11942a837c28f58ea7cbfbb37280e2
    name: operator
    type: application
    urls:
    - https://benfiola.github.io/access-operator/charts/operator-0.1.0-rc.10.tgz
    version: 0.1.0-rc.10
  - apiVersion: v2
    appVersion: 0.1.0-rc.9
    created: "2024-11-04T22:39:47.213563735Z"
    description: Manages external access into benfiola's homelab
    digest: 336d3df8be605542d0c6b7d225d25acdc041f213bce4df51456ac51666085abd
    name: operator
    type: application
    urls:
    - https://benfiola.github.io/access-operator/charts/operator-0.1.0-rc.9.tgz
    version: 0.1.0-rc.9
  - apiVersion: v2
    appVersion: 0.1.0-rc.8
    created: "2024-11-04T22:39:47.213125658Z"
    description: Manages external access into benfiola's homelab
    digest: 0328e32fffcc91bccb11b1e096d347f83ac4a967ea0888edf2ad79525c7d39fc
    name: operator
    type: application
    urls:
    - https://benfiola.github.io/access-operator/charts/operator-0.1.0-rc.8.tgz
    version: 0.1.0-rc.8
  - apiVersion: v2
    appVersion: 0.1.0-rc.7
    created: "2024-11-04T22:39:47.212710653Z"
    description: Manages external access into benfiola's homelab
    digest: 38a7bcd8ed16d47234f9e064827e7f36f1e24ce4a6708ce7e1760179239e73a4
    name: operator
    type: application
    urls:
    - https://benfiola.github.io/access-operator/charts/operator-0.1.0-rc.7.tgz
    version: 0.1.0-rc.7
  - apiVersion: v2
    appVersion: 0.1.0-rc.3
    created: "2024-11-04T22:39:47.212240205Z"
    description: Manages external access into benfiola's homelab
    digest: b0f41d6a08ff0025f92b383ef0da5c35aba44bc227f2668595a0a851b9d56aba
    name: operator
    type: application
    urls:
    - https://benfiola.github.io/access-operator/charts/operator-0.1.0-rc.3.tgz
    version: 0.1.0-rc.3
  - apiVersion: v2
    appVersion: 0.1.0-rc.2
    created: "2024-11-04T22:39:47.211837032Z"
    description: Manages external access into benfiola's homelab
    digest: e46085e4c085ca5ecbcd864be883044a4307f1f7cf1e5ab07b60317c767ae8a0
    name: operator
    type: application
    urls:
    - https://benfiola.github.io/access-operator/charts/operator-0.1.0-rc.2.tgz
    version: 0.1.0-rc.2
  - apiVersion: v2
    appVersion: 0.1.0-rc.1
    created: "2024-11-04T22:39:47.210541645Z"
    description: Manages external access into benfiola's homelab
    digest: 739dea5e1d0cebaed1c71ea795a625a5bbb876b0e874936cd39442d8c904044e
    name: operator
    type: application
    urls:
    - https://benfiola.github.io/access-operator/charts/operator-0.1.0-rc.1.tgz
    version: 0.1.0-rc.1
generated: "2024-11-04T22:39:47.204959936Z"
